[package]
name = "inseki"
version = "0.1.0"
authors = ["hyoi <hyoi.kaz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_canvas = "0.1.0"
bevy_prototype_lyon = "0.3.1"
heron = { version = "0.7.0", default-features = false, features = ["2d"] }
#heron = { version = "0.7.0", default-features = false, features = ["2d","debug"] }
rand = "0.8.3"